language: fortran

sudo: required

addons:
  apt:
    packages:
      - mpich
      - libmpich-dev
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - python3

install:
  - pip3 install pytest

env:
  - TESTS=1
  - STYLE=1

script:
  - bash bin/travis.sh
